name: Deploy changes to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build_pages:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
        
      - name: Install all dependencies
        run: npm install
        
      - name: Build
        run: npm run build
      
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: main
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
