name: Deploy changes to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
